"use client";
import { useMemo, useState } from "react";
import type { BankTransaction, BudgetLine, Expense, InventoryFunding, Invoice, ManagementKpiSnapshot, VehicleProfitability } from "@/types";
import { agedReceivables, invoiceOpenAmount, isOverdue } from "@/lib/finance/business";
import { eur } from "@/lib/format";
import { centsToEuros, signedCentsToEuros } from "@/lib/money";

export function FinanceDashboard({invoices,transactions,expenses,funding,profitability,budgets,kpis}:{invoices:Invoice[];transactions:BankTransaction[];expenses:Expense[];funding:InventoryFunding[];profitability:VehicleProfitability[];budgets:BudgetLine[];kpis:ManagementKpiSnapshot[]}){
 const [period,setPeriod]=useState(kpis.at(-1)?.period??"2026-07"); const current=kpis.find(k=>k.period===period)??kpis.at(-1)!;
 const openReceivables=invoices.filter(i=>i.kind==="sales").reduce((s,i)=>s+invoiceOpenAmount(i),0); const openPayables=invoices.filter(i=>i.kind==="purchase").reduce((s,i)=>s+invoiceOpenAmount(i),0);
 const cashFlowCents=transactions.reduce((s,t)=>s+t.amountCents,0); const activeFunding=funding.filter(f=>f.status==="active").reduce((s,f)=>s+f.principalEur+f.accruedInterestEur+f.feesEur,0);
 const age=agedReceivables(invoices); const topCars=[...profitability].sort((a,b)=>b.grossContributionEur-a.grossContributionEur);
 const expenseTotal=expenses.filter(e=>e.status!=="rejected").reduce((s,e)=>s+e.grossEur,0);
 const forecast=budgets.reduce((s,b)=>s+b.forecastEur,0), budget=budgets.reduce((s,b)=>s+b.budgetEur,0);
 const maxRevenue=Math.max(...kpis.map(k=>k.revenueEur));
 return <div className="financeWorkspace">
  <div className="toolbar"><label>Periode<select value={period} onChange={e=>setPeriod(e.target.value)}>{kpis.map(k=><option key={k.period}>{k.period}</option>)}</select></label><span className="modeBadge live">management view</span></div>
  <div className="metrics financeMetrics"><div className="metric"><strong>{eur.format(current.revenueEur)}</strong><span>omzet</span></div><div className="metric"><strong>{eur.format(current.grossProfitEur)}</strong><span>brutowinst</span></div><div className="metric"><strong>{eur.format(current.ebitdaEur)}</strong><span>EBITDA</span></div><div className="metric"><strong>{eur.format(current.cashEur)}</strong><span>liquide middelen</span></div></div>
  <div className="financeGrid"><section className="panel"><div className="panelHeader"><div><p className="eyebrow">Resultaat</p><h2>Omzet en EBITDA</h2></div><strong>{((current.ebitdaEur/current.revenueEur)*100).toFixed(1)}%</strong></div><div className="miniChart">{kpis.map(k=><div key={k.period}><span style={{height:`${Math.max(12,k.revenueEur/maxRevenue*100)}%`}}/><b style={{height:`${Math.max(6,k.ebitdaEur/maxRevenue*100)}%`}}/><small>{k.period.slice(5)}</small></div>)}</div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">Liquiditeit</p><h2>Kaspositie</h2></div><strong className={cashFlowCents>=0?"positive":"negative"}>{eur.format(signedCentsToEuros(cashFlowCents))}</strong></div><div className="financeRows"><p><span>Openstaande debiteuren</span><b>{eur.format(centsToEuros(openReceivables))}</b></p><p><span>Openstaande crediteuren</span><b>{eur.format(centsToEuros(openPayables))}</b></p><p><span>Actieve voorraadfinanciering</span><b>{eur.format(activeFunding)}</b></p><p><span>Geboekte kosten</span><b>{eur.format(expenseTotal)}</b></p></div></section></div>
  <div className="financeGrid"><section className="panel"><div className="panelHeader"><div><p className="eyebrow">Debiteuren</p><h2>Ouderdomsanalyse</h2></div><span>{invoices.filter(i=>isOverdue(i)).length} te laat</span></div><div className="agingGrid"><div><span>Niet vervallen</span><b>{eur.format(centsToEuros(age.current))}</b></div><div><span>1–30 dagen</span><b>{eur.format(centsToEuros(age.days1to30))}</b></div><div><span>31–60 dagen</span><b>{eur.format(centsToEuros(age.days31to60))}</b></div><div><span>61+ dagen</span><b>{eur.format(centsToEuros(age.days61plus))}</b></div></div></section>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">Forecast</p><h2>Budget versus verwachting</h2></div><strong className={forecast<=budget?"positive":"negative"}>{eur.format(forecast-budget)}</strong></div>{budgets.map(b=><div className="budgetRow" key={b.id}><span>{b.category.replaceAll("_"," ")}</span><div><i style={{width:`${Math.min(100,b.actualEur/Math.max(1,b.budgetEur)*100)}%`}}/></div><b>{eur.format(b.actualEur)} / {eur.format(b.budgetEur)}</b></div>)}</section></div>
  <section className="panel"><div className="panelHeader"><div><p className="eyebrow">Unit economics</p><h2>Winst per auto</h2></div><span>na directe kosten</span></div><div className="profitTable"><header><span>Voertuig</span><span>Omzet</span><span>Voorraaddagen</span><span>Bijdrage</span><span>Marge</span></header>{topCars.map(v=><article key={v.vehicleId}><span><b>{v.vehicleLabel}</b><small>{v.vehicleId}</small></span><span>{eur.format(v.salePriceEur)}</span><span className={v.stockDays>75?"negative":""}>{v.stockDays} dagen</span><span className={v.grossContributionEur>2500?"positive":"negative"}>{eur.format(v.grossContributionEur)}</span><span>{v.contributionPercent.toFixed(1)}%</span></article>)}</div></section>
 </div>
}
