"use client";
import { useMemo, useState } from "react";
import type { Invoice, InvoiceStatus } from "@/types";
import { invoiceOpenAmount, isOverdue, vatBreakdown } from "@/lib/finance/business";
import { eur } from "@/lib/format";
import { centsToEuros } from "@/lib/money";
const labels:Record<InvoiceStatus,string>={draft:"Concept",sent:"Verzonden",partially_paid:"Deels betaald",paid:"Betaald",overdue:"Te laat",cancelled:"Geannuleerd"};
export function InvoiceCenter({initialInvoices}:{initialInvoices:Invoice[]}){
 const [invoices,setInvoices]=useState(initialInvoices); const [filter,setFilter]=useState("all"); const [query,setQuery]=useState("");
 const list=useMemo(()=>invoices.filter(i=>(filter==="all"||i.kind===filter||i.status===filter)&&`${i.number} ${i.customerOrSupplier}`.toLowerCase().includes(query.toLowerCase())),[invoices,filter,query]);
 function markPaid(id:string){setInvoices(rows=>rows.map(i=>i.id===id?{...i,status:"paid",paidCents:i.totalCents,updatedAt:new Date().toISOString()}:i))}
 return <div className="invoiceCenter"><div className="toolbar"><input placeholder="Zoek factuur of relatie" value={query} onChange={e=>setQuery(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Alles</option><option value="sales">Verkoop</option><option value="purchase">Inkoop</option><option value="sent">Open</option><option value="paid">Betaald</option></select><button className="button" type="button">+ Nieuwe factuur</button></div>
 <div className="metrics"><div className="metric"><strong>{eur.format(centsToEuros(invoices.filter(i=>i.kind==="sales").reduce((s,i)=>s+invoiceOpenAmount(i),0)))}</strong><span>te ontvangen</span></div><div className="metric"><strong>{eur.format(centsToEuros(invoices.filter(i=>i.kind==="purchase").reduce((s,i)=>s+invoiceOpenAmount(i),0)))}</strong><span>te betalen</span></div><div className="metric"><strong>{eur.format(centsToEuros(invoices.reduce((s,i)=>s+i.vatCents,0)))}</strong><span>btw in documenten</span></div><div className="metric"><strong>{invoices.filter(i=>isOverdue(i)).length}</strong><span>vervallen</span></div></div>
 <div className="invoiceList">{list.map(i=>{const open=invoiceOpenAmount(i);return <article key={i.id} className={isOverdue(i)?"overdue":""}><div><span className="eyebrow">{i.kind} · {i.number}</span><h3>{i.customerOrSupplier}</h3><small>{new Date(i.invoiceDate).toLocaleDateString("nl-NL")} · vervalt {new Date(i.dueDate).toLocaleDateString("nl-NL")}</small></div><div className="invoiceAmounts"><b>{eur.format(centsToEuros(i.totalCents))}</b><small>open {eur.format(centsToEuros(open))}</small></div><div><span className={`statusPill ${isOverdue(i)?"overdue":i.status}`}>{isOverdue(i)?"Te laat":labels[i.status]}</span>{open>0&&<button className="textLink" type="button" onClick={()=>markPaid(i.id)}>Markeer betaald</button>}</div><details><summary>Regels en btw</summary>{i.lines.map(l=><p key={l.id}><span>{l.quantity} × {l.description} ({l.vatPercent}% btw)</span><b>{eur.format(centsToEuros(Math.round(l.quantity*l.unitPriceCents)))}</b></p>)}{vatBreakdown(i.lines).map(v=><p key={v.rate}><span>Btw {v.rate}%</span><b>{eur.format(centsToEuros(v.vatCents))}</b></p>)}</details></article>})}</div></div>
}
