import type { Vehicle } from "@/types";

export const vehicles: Vehicle[] = [
  {
    id: "VV-2026-001",
    slug: "toyota-corolla-touring-sports-18-hybrid-dynamic",
    brand: "Toyota",
    model: "Corolla Touring Sports",
    trim: "1.8 Hybrid Dynamic",
    year: 2022,
    mileageKm: 58200,
    priceEur: 26950,
    monthlyPriceEur: 429,
    driveType: "full-hybrid",
    fuelType: "Benzine / elektrisch",
    transmission: "Automaat",
    bodyStyle: "Stationwagon",
    color: "Pearl White",
    batteryHealthPercent: 96,
    consumptionPer100Km: 4.5,
    annualSavingEur: 1380,
    warrantyMonths: 12,
    maintenanceHistory: "complete",
    images: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1600&q=85"],
    highlights: ["Adaptieve cruisecontrol", "Apple CarPlay", "Camera", "LED"],
    status: "available",
    locationCode: "VOLT_VROOM_GRONINGEN",
    updatedAt: new Date().toISOString()
  },
  {
    id: "VV-2026-002",
    slug: "lexus-ux-250h-business-line",
    brand: "Lexus",
    model: "UX 250h",
    trim: "Business Line",
    year: 2021,
    mileageKm: 71100,
    priceEur: 28950,
    monthlyPriceEur: 469,
    driveType: "full-hybrid",
    fuelType: "Benzine / elektrisch",
    transmission: "Automaat",
    bodyStyle: "SUV",
    color: "Sonic Titanium",
    batteryHealthPercent: 95,
    consumptionPer100Km: 5.1,
    annualSavingEur: 1210,
    warrantyMonths: 12,
    maintenanceHistory: "complete",
    images: ["https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=1600&q=85"],
    highlights: ["Lexus Safety System+", "Stoelverwarming", "Camera", "Premium audio"],
    status: "available",
    locationCode: "VOLT_VROOM_GRONINGEN",
    updatedAt: new Date().toISOString()
  }
];
