"use client";
import { useEffect, useMemo, useState } from "react";
import type { Appointment, Lead, LeadActivity, Quote, TradeIn } from "@/types";
import { listLeads, saveLead } from "@/lib/repositories/lead-repository";
import { listLeadActivities, listLeadAppointments, listLeadQuotes, listLeadTradeIns, saveAppointment, saveLeadActivity, saveQuote, saveTradeIn } from "@/lib/repositories/crm-repository";
import { createQuoteId, defaultQuoteLines, quoteTotals, scoreLead } from "@/lib/sales-engine";
import { eur } from "@/lib/format";

export function LeadWorkspace({id}:{id:string}){
 const [lead,setLead]=useState<Lead>(); const [activities,setActivities]=useState<LeadActivity[]>([]); const [appointments,setAppointments]=useState<Appointment[]>([]); const [quotes,setQuotes]=useState<Quote[]>([]); const [tradeIns,setTradeIns]=useState<TradeIn[]>([]); const [note,setNote]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState<string>();
 useEffect(()=>{let active=true;Promise.all([listLeads(),listLeadActivities(id),listLeadAppointments(id),listLeadQuotes(id),listLeadTradeIns(id)]).then(([leads,a,ap,q,t])=>{if(!active)return;setLead(leads.find(x=>x.id===id));setActivities(a);setAppointments(ap);setQuotes(q);setTradeIns(t);setError(undefined)}).catch(e=>active&&setError(e instanceof Error?e.message:"CRM laden mislukt.")).finally(()=>active&&setLoading(false));return()=>{active=false}},[id]);
 const score=useMemo(()=>lead?scoreLead(lead):undefined,[lead]); if(loading)return <div className="panel">CRM laden…</div>; if(error)return <div className="panel">{error}</div>; if(!lead)return <div className="panel">Lead niet gevonden.</div>; const currentLead: Lead = lead;
 async function log(type:LeadActivity["type"],summary:string,body?:string){const item:LeadActivity={id:crypto.randomUUID(),leadId:id,type,summary,body,createdAt:new Date().toISOString()};await saveLeadActivity(item);setActivities(current=>[item,...current])}
 async function addNote(){if(!note.trim())return;await log("note","Notitie toegevoegd",note);setNote("")}
 async function plan(){const start=new Date(Date.now()+86400000);start.setHours(11,0,0,0);const a:Appointment={id:crypto.randomUUID(),leadId:id,vehicleId:currentLead.vehicleId,type:"test_drive",startAt:start.toISOString(),endAt:new Date(start.getTime()+3600000).toISOString(),status:"planned",location:"Volt & Vroom Groningen"};await saveAppointment(a);setAppointments(current=>[...current,a].sort((x,y)=>x.startAt.localeCompare(y.startAt)));const next:Lead={...currentLead,status:"appointment",nextActionAt:a.startAt};await saveLead(next);setLead(next);await log("appointment","Proefrit ingepland")}
 async function quote(){const q:Quote={id:createQuoteId(),leadId:id,vehicleId:currentLead.vehicleId,status:"draft",lines:defaultQuoteLines(24950),discountEur:0,tradeInCreditEur:tradeIns[0]?.offeredValueEur??0,validUntil:new Date(Date.now()+7*86400000).toISOString(),createdAt:new Date().toISOString()};await saveQuote(q);setQuotes(current=>[q,...current]);await log("quote","Conceptofferte aangemaakt")}
 async function trade(){const t:TradeIn={id:crypto.randomUUID(),leadId:id,licensePlate:"",mileageKm:0,status:"requested",photos:[],createdAt:new Date().toISOString()};await saveTradeIn(t);setTradeIns(current=>[t,...current]);const next:Lead={...currentLead,hasTradeIn:true};await saveLead(next);setLead(next);await log("trade_in","Inruildossier gestart")}
 return <div className="leadWorkspace"><section className="panel"><div className="panelHeader"><div><p className="eyebrow">Leadprofiel</p><h2>{lead.name}</h2><p className="muted">{lead.phone||"Geen telefoon"} · {lead.email||"Geen e-mail"}</p></div><div className={`scoreRing ${score?.temperature}`}><strong>{score?.score}</strong><span>{score?.temperature}</span></div></div><div className="actions"><button className="button" onClick={()=>void log("call","Belactie geregistreerd")}>Belactie</button><button className="button secondary" onClick={()=>void log("whatsapp","WhatsApp voorbereid")}>WhatsApp</button><button className="button secondary" onClick={()=>void plan()}>Plan proefrit</button><button className="button secondary" onClick={()=>void quote()}>Maak offerte</button><button className="button secondary" onClick={()=>void trade()}>Start inruil</button></div><div className="reasonList">{score?.reasons.map(r=><span key={r}>{r}</span>)}</div></section><div className="workspaceGrid"><section className="panel"><h2>Activiteit</h2><div className="noteComposer"><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Voeg een interne notitie toe…"/><button className="button" onClick={()=>void addNote()}>Opslaan</button></div><div className="timeline">{activities.length?activities.map(a=><article key={a.id}><i/><div><strong>{a.summary}</strong><p>{a.body}</p><small>{new Date(a.createdAt).toLocaleString("nl-NL")}</small></div></article>):<p className="muted">Nog geen activiteiten.</p>}</div></section><aside className="stack"><section className="panel"><h3>Afspraken</h3>{appointments.map(a=><div className="miniRecord" key={a.id}><strong>{a.type.replace("_"," ")}</strong><span>{new Date(a.startAt).toLocaleString("nl-NL")}</span></div>)}</section><section className="panel"><h3>Offertes</h3>{quotes.map(q=>{const t=quoteTotals(q.lines,q.discountEur,q.tradeInCreditEur);return <div className="miniRecord" key={q.id}><strong>{q.id}</strong><span>{eur.format(t.total)} · {q.status}</span></div>})}</section><section className="panel"><h3>Inruil</h3>{tradeIns.map(t=><div className="miniRecord" key={t.id}><strong>{t.licensePlate||"Kenteken nog invullen"}</strong><span>{t.status}</span></div>)}</section></aside></div></div>
}
