"use client";
import { useEffect, useMemo, useState } from "react";
import type { Appointment, Lead, LeadActivity, Quote, TradeIn } from "@/types";
import { getActivities,getAppointments,getLeads,getQuotes,getTradeIns,saveActivities,saveAppointments,saveLeads,saveQuotes,saveTradeIns } from "@/lib/demo-store";
import { createQuoteId, defaultQuoteLines, quoteTotals, scoreLead } from "@/lib/sales-engine";
import { eur } from "@/lib/format";

export function LeadWorkspace({id}:{id:string}){
 const [lead,setLead]=useState<Lead>(); const [activities,setActivities]=useState<LeadActivity[]>([]); const [appointments,setAppointments]=useState<Appointment[]>([]); const [quotes,setQuotes]=useState<Quote[]>([]); const [tradeIns,setTradeIns]=useState<TradeIn[]>([]); const [note,setNote]=useState("");
 useEffect(()=>{setLead(getLeads().find(x=>x.id===id));setActivities(getActivities().filter(x=>x.leadId===id));setAppointments(getAppointments().filter(x=>x.leadId===id));setQuotes(getQuotes().filter(x=>x.leadId===id));setTradeIns(getTradeIns().filter(x=>x.leadId===id))},[id]);
 const score=useMemo(()=>lead?scoreLead(lead):undefined,[lead]); if(!lead)return <div className="panel">Lead niet gevonden.</div>; const currentLead: Lead = lead;
 function log(type:LeadActivity["type"],summary:string,body?:string){const item={id:crypto.randomUUID(),leadId:id,type,summary,body,createdAt:new Date().toISOString()};const all=[item,...getActivities()];saveActivities(all);setActivities(all.filter(x=>x.leadId===id))}
 function addNote(){if(!note.trim())return;log("note","Notitie toegevoegd",note);setNote("")}
 function plan(){const start=new Date(Date.now()+86400000);start.setHours(11,0,0,0);const a:Appointment={id:crypto.randomUUID(),leadId:id,vehicleId:currentLead.vehicleId,type:"test_drive",startAt:start.toISOString(),endAt:new Date(start.getTime()+3600000).toISOString(),status:"planned",location:"Volt & Vroom Groningen"};const all=[a,...getAppointments()];saveAppointments(all);setAppointments(all.filter(x=>x.leadId===id));log("appointment","Proefrit ingepland")}
 function quote(){const q:Quote={id:createQuoteId(),leadId:id,vehicleId:currentLead.vehicleId,status:"draft",lines:defaultQuoteLines(24950),discountEur:0,tradeInCreditEur:tradeIns[0]?.offeredValueEur??0,validUntil:new Date(Date.now()+7*86400000).toISOString(),createdAt:new Date().toISOString()};const all=[q,...getQuotes()];saveQuotes(all);setQuotes(all.filter(x=>x.leadId===id));log("quote","Conceptofferte aangemaakt")}
 function trade(){const t:TradeIn={id:crypto.randomUUID(),leadId:id,licensePlate:"",mileageKm:0,status:"requested",photos:[],createdAt:new Date().toISOString()};const all=[t,...getTradeIns()];saveTradeIns(all);setTradeIns(all.filter(x=>x.leadId===id));const next: Lead={...currentLead,hasTradeIn:true};setLead(next);const leads=getLeads().map(x=>x.id===id?next:x);saveLeads(leads);log("trade_in","Inruildossier gestart")}
 return <div className="leadWorkspace"><section className="panel"><div className="panelHeader"><div><p className="eyebrow">Leadprofiel</p><h2>{lead.name}</h2><p className="muted">{lead.phone||"Geen telefoon"} · {lead.email||"Geen e-mail"}</p></div><div className={`scoreRing ${score?.temperature}`}><strong>{score?.score}</strong><span>{score?.temperature}</span></div></div><div className="actions"><button className="button" onClick={()=>log("call","Belactie geregistreerd")}>Belactie</button><button className="button secondary" onClick={()=>log("whatsapp","WhatsApp voorbereid")}>WhatsApp</button><button className="button secondary" onClick={plan}>Plan proefrit</button><button className="button secondary" onClick={quote}>Maak offerte</button><button className="button secondary" onClick={trade}>Start inruil</button></div><div className="reasonList">{score?.reasons.map(r=><span key={r}>{r}</span>)}</div></section><div className="workspaceGrid"><section className="panel"><h2>Activiteit</h2><div className="noteComposer"><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Voeg een interne notitie toe…"/><button className="button" onClick={addNote}>Opslaan</button></div><div className="timeline">{activities.length?activities.map(a=><article key={a.id}><i/><div><strong>{a.summary}</strong><p>{a.body}</p><small>{new Date(a.createdAt).toLocaleString("nl-NL")}</small></div></article>):<p className="muted">Nog geen activiteiten.</p>}</div></section><aside className="stack"><section className="panel"><h3>Afspraken</h3>{appointments.map(a=><div className="miniRecord" key={a.id}><strong>{a.type.replace("_"," ")}</strong><span>{new Date(a.startAt).toLocaleString("nl-NL")}</span></div>)}</section><section className="panel"><h3>Offertes</h3>{quotes.map(q=>{const t=quoteTotals(q.lines,q.discountEur,q.tradeInCreditEur);return <div className="miniRecord" key={q.id}><strong>{q.id}</strong><span>{eur.format(t.total)} · {q.status}</span></div>})}</section><section className="panel"><h3>Inruil</h3>{tradeIns.map(t=><div className="miniRecord" key={t.id}><strong>{t.licensePlate||"Kenteken nog invullen"}</strong><span>{t.status}</span></div>)}</section></aside></div></div>
}
