"use client";
import { useEffect, useState } from "react";
import type { Appointment, AutomationRule, Quote } from "@/types";
import { getAppointments,getAutomationRules,getQuotes,saveAutomationRules } from "@/lib/demo-store";
import { quoteTotals } from "@/lib/sales-engine";
import { eur } from "@/lib/format";
export function AppointmentList(){const [items,setItems]=useState<Appointment[]>([]);useEffect(()=>setItems(getAppointments()),[]);return <div className="recordGrid">{items.length?items.map(a=><article className="panel" key={a.id}><span className="statusPill">{a.status}</span><h3>{a.type.replace("_"," ")}</h3><p>{new Date(a.startAt).toLocaleString("nl-NL")}</p><small>{a.location}</small></article>):<div className="panel"><p className="muted">Nog geen afspraken. Plan deze vanuit een leaddossier.</p></div>}</div>}
export function QuoteList(){const [items,setItems]=useState<Quote[]>([]);useEffect(()=>setItems(getQuotes()),[]);return <div className="recordGrid">{items.length?items.map(q=>{const t=quoteTotals(q.lines,q.discountEur,q.tradeInCreditEur);return <article className="panel" key={q.id}><span className="statusPill">{q.status}</span><h3>{q.id}</h3><p className="price">{eur.format(t.total)}</p><small>Geldig tot {new Date(q.validUntil).toLocaleDateString("nl-NL")}</small></article>}):<div className="panel"><p className="muted">Nog geen offertes. Maak deze vanuit een leaddossier.</p></div>}</div>}
export function AutomationList(){const [items,setItems]=useState<AutomationRule[]>([]);useEffect(()=>setItems(getAutomationRules()),[]);function toggle(id:string){const next=items.map(x=>x.id===id?{...x,enabled:!x.enabled}:x);setItems(next);saveAutomationRules(next)}return <div className="automationList">{items.map(a=><article className="panel automationRow" key={a.id}><div><p className="eyebrow">{a.trigger} · {a.delayMinutes} min</p><h3>{a.name}</h3><p className="muted">{a.template}</p></div><label className="switch"><input type="checkbox" checked={a.enabled} onChange={()=>toggle(a.id)}/><span>{a.enabled?"Actief":"Uit"}</span></label></article>)}</div>}
